# Generated by Django 3.0.5 on 2020-05-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0051_tag_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='restauranttag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
